### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Samwisedumb** [Haskiez/hacking-the-game#1]
The files _index.html_ and _game.js_ make references to a few files missing from the repo:

- _styleSheet.css_
- _resources/gridBackground.svg_
- _resources/knight.png_

**Comment by Haskiez** [comment]
Oh sorry haha I'll add those to the repo today. Then again, the styleSheet
isn't necessary since I took everything out of it and the images are just
placeholders so you could put anything in there.
